---
title: "HIV dataset"
author: Yuqi Wang
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

## HIV data from NYC open data
```{r}
nyc_hiv = 
  GET("https://data.cityofnewyork.us/resource/fju2-rdad.csv",
      query = list("$limit" = 7000)) %>% 
  content("parsed")

nyc_hiv %>% 
  filter(year == 2013) %>% view()
```


```{r}
library(pdftools)
url_13 = "https://www1.nyc.gov/assets/doh/downloads/pdf/ah/surveillance2013-table-all.pdf"

title =  pdf_text(url_13) %>% 
  .[[2]] %>% str_split(., "\n") %>% .[[1]] %>% 
  .[4]

data = pdf_text(url_13) %>% 
  .[[2]] %>% str_split(., "\n") %>% 
  as_tibble(.name_repair = make.names) %>% 
  mutate(category = str_sub(X, 0,75),
         total_hiv_diag_N = str_sub(X,76,85),
         total_hiv_diag_per = str_sub(X,86,94),
         without_aids_N = str_sub(X,95,104),
         without_aids_per = str_sub(X,105,115),
         concurrent_aids_N = str_sub(X,116,126),
         concurrent_aids_per = str_sub(X,127,137),
         aids_N = str_sub(X,138,149),
         aids_per = str_sub(X,150,161),
         plwha_N = str_sub(X,162,175),
         plwha_per = str_sub(X,176,185),
         death_N = str_sub(X,186,193),
         death_per = str_sub(X,194)
         ) %>% 
  select(-X) %>% 
  .[-c(1:10),] %>% 
  filter(row_number() <= n()-2) %>% 
  mutate_all(funs(str_replace(.,",", ""))) %>% 
  mutate_all(str_squish) %>% 
  mutate_at(vars(-category), as.numeric)

data = cbind(title, data)
data %>% view()

#data =  pdf_text(url) %>% 
#  .[[2]] %>% str_split(., "\n") %>% 
#  as_tibble(.name_repair = make.names)
#data[11,1] %>% pull(X)
#str_locate_all(data[11,1] %>% pull(X), "1,852")

```

Function to extract data:

```{r}
pdf_scrape = function(pdf, report_year){
  title = pdf %>% 
    str_split(., "\n") %>% .[[1]] %>% 
  .[4]
  
  year = report_year
  
  data = pdf %>% str_split(., "\n") %>% 
  as_tibble(.name_repair = make.names) %>% 
  mutate(category = str_sub(X, 0,75),
         total_hiv_diag_N = str_sub(X,76,85),
         total_hiv_diag_per = str_sub(X,86,94),
         without_aids_N = str_sub(X,95,104),
         without_aids_per = str_sub(X,105,115),
         concurrent_aids_N = str_sub(X,116,126),
         concurrent_aids_per = str_sub(X,127,137),
         aids_N = str_sub(X,138,149),
         aids_per = str_sub(X,150,161),
         plwha_N = str_sub(X,162,175),
         plwha_per = str_sub(X,176,185),
         death_N = str_sub(X,186,193),
         death_per = str_sub(X,194)
         ) %>% 
  select(-X) %>% 
  .[-c(1:10),] %>% 
  filter(row_number() <= n()-2) %>% 
  mutate_all(funs(str_replace(.,",", ""))) %>% 
  mutate_all(str_squish) %>% 
  mutate_at(vars(-category), as.numeric)
  
  cbind(year, title, data) %>% 
    as_tibble()
}

data_clean = function(clean_data){
  clean_data %>% 
  as_tibble() %>% 
  filter(title %in% c("Table 1.1. New York City (All)")) %>% 
  filter(!is.na(total_hiv_diag_N)) %>%
  filter(category != "Unknown") %>% 
  mutate(
    sex = case_when(
      category == "Male" ~ "Male",
      category == "Female" ~ "Female",
      category == "Transgender" ~ "Transgender",
      TRUE ~ "All"
    ),
    race = case_when(
      category == "Black" ~ "Black",
      category == "Latino/Hispanic" ~ "Latino/Hispanic",
      category == "White" ~ "White",
      category == "Asian/Pacific Islander" ~ "Asian/Pacific Islander",
      category == "Native American" ~ "Native American",
      category == "Multiracial" ~ "Multiracial",
      TRUE ~ "All"
    ),
    borough = case_when(
      category == "Bronx" ~ "Bronx",
      category == "Brooklyn" ~ "Brooklyn",
      category == "Manhattan" ~ "Manhattan",
      category == "Queens" ~ "Queens",
      category == "Staten Island" ~ "Staten Island",
      category == "Outside NYC" ~ "Outside NYC",
      TRUE ~ "All"
    ),
    age_cat = case_when(
      category == "0-12" ~ "0-12",
      category == "13-19" ~ "13-19",
      category == "20-29" ~ "20-29",
      category == "30-39" ~ "30-39",
      category == "40-49" ~ "40-49",
      category == "50-59" ~ "50-59",
      category == "60+" ~ "60+",
      TRUE ~ "All"
    )
  ) %>% 
  relocate(borough, sex, race, age_cat) %>%
  #select(-category, -title) %>%
  head(23)
}

```

URL function:
```{r}
url_list = list(
  url_11 = "https://www1.nyc.gov/assets/doh/downloads/pdf/ah/surveillance2011-table-all.pdf",
  url_12 = "https://www1.nyc.gov/assets/doh/downloads/pdf/ah/surveillance2012-table-all.pdf",
  url_13 = "https://www1.nyc.gov/assets/doh/downloads/pdf/ah/surveillance2013-table-all.pdf",
  url_14 = "https://www1.nyc.gov/assets/doh/downloads/pdf/ah/surveillance2014-table-all.pdf",
  url_15 = "https://www1.nyc.gov/assets/doh/downloads/pdf/ah/surveillance2015-table-all.pdf",
  url_16 = "https://www1.nyc.gov/assets/doh/downloads/pdf/ah/surveillance2016-table-all.pdf",
  url_17 = "https://www1.nyc.gov/assets/doh/downloads/pdf/ah/surveillance2017-table-all.pdf"
)
```


HIV dataset for 2011: OK!!!

```{r}
pdf =  pdf_text(url_list$url_11) 
list = map(.x = pdf[-1], ~pdf_scrape(.x, 2011)) 
clean11 = as.data.frame(do.call(rbind, list))

data11 = data_clean(clean11)
```


HIV dataset for 2012: OK!!!

```{r}
title =  pdf_text(url_list$url_12) %>% 
  .[[2]] %>% str_split(., "\n") %>% .[[1]] %>% 
  .[4]

data12 = pdf_text(url_list$url_12) %>% 
  .[[2]] %>% str_split(., "\n") %>% 
  as_tibble(.name_repair = make.names) %>% 
  mutate(category = str_sub(X, 0,74),
         total_hiv_diag_N = str_sub(X,76,80),
         total_hiv_diag_per = str_sub(X,93,97),
         without_aids_N = str_sub(X,93,100),
         without_aids_per = str_sub(X,102,105),
         concurrent_aids_N = str_sub(X,116,126),
         concurrent_aids_per = str_sub(X,127,135),
         aids_N = str_sub(X,137,144),
         aids_per = str_sub(X,150,158),
         plwha_N = str_sub(X,161,171),
         plwha_per = str_sub(X,176,177),
         death_N = str_sub(X,185,190),
         death_per = str_sub(X,194)
         ) %>% 
  select(-X) %>% 
  .[-c(1:10),] %>% 
  filter(row_number() <= n()-2) %>% 
  mutate_all(funs(str_replace(.,",", ""))) %>% 
  mutate_all(str_squish) %>% 
  mutate_at(vars(-category), as.numeric)

data12 = data_clean(data12) %>% 
  mutate(year = 2012)
```


HIV dataset for 2013: OK!!!

```{r}
pdf =  pdf_text(url_list$url_13) 
list = map(.x = pdf[-1], ~pdf_scrape(.x, 2013)) 
clean13 = as.data.frame(do.call(rbind, list))

data13 = data_clean(clean13)
```

HIV dataset for 2014: OK!!!

```{r}
data14 = pdf_text(url_list$url_14) %>% 
  .[[2]] %>% str_split(., "\n") %>% 
  as_tibble(.name_repair = make.names) %>% 
  mutate(category = str_sub(X, 0,73),
         total_hiv_diag_N = str_sub(X,74,83),
         total_hiv_diag_per = str_sub(X,84,88),
         without_aids_N = str_sub(X,89,101),
         without_aids_per = str_sub(X,102,113),
         concurrent_aids_N = str_sub(X,114,122),
         concurrent_aids_per = str_sub(X,123,133),
         aids_N = str_sub(X,134,145),
         aids_per = str_sub(X,146,156),
         plwha_N = str_sub(X,157,163),
         plwha_per = str_sub(X,171,179),
         death_N = str_sub(X,180,187),
         death_per = str_sub(X,188)
         ) %>% 
  select(-X) %>% 
  .[-c(1:10),] %>% 
  filter(row_number() <= n()-2) %>% 
  mutate_all(funs(str_replace(.,",", ""))) %>% 
  mutate_all(str_squish) %>% 
  mutate_at(vars(-category), as.numeric)

data14 = data_clean(data14) %>% 
  mutate(
    sex = case_when(
      category == "Men" ~ "Male",
      category == "Women" ~ "Female",
      category == "Transgender" ~ "Transgender",
      TRUE ~ "All")
  )%>% 
  mutate(year = 2014)

```


HIV dataset for 2015:

```{r}
data15 = pdf_text(url_list$url_15) %>% 
  .[[2]] %>% str_split(., "\n") %>% 
  as_tibble(.name_repair = make.names) %>% 
  mutate(category = str_sub(X, 0,73),
         total_hiv_diag_N = str_sub(X,74,83),
         total_hiv_diag_per = str_sub(X,84,88),
         without_aids_N = str_sub(X,89,101),
         without_aids_per = str_sub(X,102,113),
         concurrent_aids_N = str_sub(X,114,122),
         concurrent_aids_per = str_sub(X,123,133),
         aids_N = str_sub(X,134,145),
         aids_per = str_sub(X,146,156),
         plwha_N = str_sub(X,157,163),
         plwha_per = str_sub(X,171,179),
         death_N = str_sub(X,180,187),
         death_per = str_sub(X,188)
         ) %>% 
  select(-X) %>% 
  .[-c(1:10),] %>% 
  filter(row_number() <= n()-2) %>% 
  mutate_all(funs(str_replace(.,",", ""))) %>% 
  mutate_all(str_squish) %>% 
  mutate_at(vars(-category), as.numeric)

data15 = data_clean(data15) %>% 
  mutate(
    sex = case_when(
      category == "Men" ~ "Male",
      category == "Women" ~ "Female",
      category == "Transgender" ~ "Transgender",
      TRUE ~ "All")
  )%>% 
  mutate(year = 2015)

```


HIV dataset for 2016:
```{r}
data16 = pdf_text(url_list$url_16) %>% 
  .[[2]] %>% str_split(., "\n") %>% 
  as_tibble(.name_repair = make.names) %>% 
  mutate(category = str_sub(X, 0,73),
         total_hiv_diag_N = str_sub(X,74,83),
         total_hiv_diag_per = str_sub(X,84,88),
         without_aids_N = str_sub(X,89,101),
         without_aids_per = str_sub(X,102,113),
         concurrent_aids_N = str_sub(X,114,122),
         concurrent_aids_per = str_sub(X,123,133),
         aids_N = str_sub(X,134,145),
         aids_per = str_sub(X,146,156),
         plwha_N = str_sub(X,157,163),
         plwha_per = str_sub(X,171,179),
         death_N = str_sub(X,180,187),
         death_per = str_sub(X,188)
         ) %>% 
  select(-X) %>% 
  .[-c(1:10),] %>% 
  filter(row_number() <= n()-2) %>% 
  mutate_all(funs(str_replace(.,",", ""))) %>% 
  mutate_all(str_squish) %>% 
  mutate_at(vars(-category), as.numeric)

data16 = data_clean(data16) %>% 
  mutate(
    sex = case_when(
      category == "Men" ~ "Male",
      category == "Women" ~ "Female",
      category == "Transgender" ~ "Transgender",
      TRUE ~ "All")
  )%>% 
  mutate(year = 2016)
```


HIV dataset for 2017:

```{r}
data17 = pdf_text(url_list$url_17) %>% 
  .[[2]] %>% str_split(., "\n") %>% 
  as_tibble(.name_repair = make.names) %>% 
  mutate(category = str_sub(X, 0,73),
         total_hiv_diag_N = str_sub(X,74,83),
         total_hiv_diag_per = str_sub(X,84,88),
         without_aids_N = str_sub(X,89,101),
         without_aids_per = str_sub(X,102,113),
         concurrent_aids_N = str_sub(X,114,122),
         concurrent_aids_per = str_sub(X,123,133),
         aids_N = str_sub(X,134,145),
         aids_per = str_sub(X,146,156),
         plwha_N = str_sub(X,157,163),
         plwha_per = str_sub(X,171,179),
         death_N = str_sub(X,180,187),
         death_per = str_sub(X,188)
         ) %>% 
  select(-X) %>% 
  .[-c(1:10),] %>% 
  filter(row_number() <= n()-2) %>% 
  mutate_all(funs(str_replace(.,",", ""))) %>% 
  mutate_all(str_squish) %>% 
  mutate_at(vars(-category), as.numeric)

data17 = data_clean(data17) %>% 
  mutate(
    sex = case_when(
      category == "Men" ~ "Male",
      category == "Women" ~ "Female",
      category == "Transgender" ~ "Transgender",
      TRUE ~ "All")
  )%>% 
  mutate(year = 2017)

data17 %>% view()
```

Combine the whole dataset together:

```{r}
data_complete = list(
  data11,
  data12,
  data13,
  data14,
  data15,
  data16,
  data17
) %>% 
  bind_rows() %>%
  select(year, borough, sex, race, age_cat, total_hiv_diag_N, aids_N, plwha_N, death_N)
  
  
  write.csv(data_complete,'data_complete.csv')
```





